import type { Metadata } from "next";
import "../globals.css";
import { FloatingNav } from "@/modules/navbar";
import { Providers } from "../ThemeProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Providers>
        <FloatingNav />
      </Providers>
      {children}
    </main>

  );
}
