export const fields = {
  initialStudyingIn: {
    School: [
      { label: "Class 12th Passed", type: "radio" },
      "Class 12th",
      "Class 11th",
      "Class 10th",
      "Class 9th",
      "Class 8th",
      "Class 7th",
      "Class 6th",
    ],
    "After 10th/UG Diploma": ["1st Year", "2nd Year", "3rd Year & Above"],
    "UG Degree/Graduation": [
      "1st Year",
      "2nd Year",
      "3rd Year",
      "4th Year",
      "5th Year & Above",
    ],
    "Graduation Complete": ["Graduate"],
    "PG Diploma/Post Graduation": ["1st Year", "2nd Year", "3rd Year & Above"],
    "PG Degree/Post Graduation": ["1st Year", "2nd Year", "3rd Year & Above"],
    "PG Complete": ["Post Graduate"],
    "Advanced Masters/Doctorate": ["1st Year", "2nd Year", "3rd Year & Above"],
  },
  after12Pass: {
    "Engineering and Architecture": [
      "B.E /B.Tech",
      "B.Arch",
      "B.Tech M.Tech",
      "B.Tech MBA",
      "B.Plan",
    ],
    "Management and Business Administration": ["BBA/BMS", "B.Sc/B.Sc (Hons)"],
    "Medicine and Allied Sciences": [
      "M.B.B.S.",
      "B.P.T.",
      "B.A.M.S.",
      "B.D.S.",
      "B.Nurs",
    ],
    Law: ["L.L.B", "B.A/B.B.A/B.Sc/B.Com LLB"],
    "Animation and Design": [
      "B.Des",
      "BFD",
      "B.I.D.",
      "B.F.Tech",
      "B.Des M.Des",
    ],
    "Media, Mass Communication and Journalism": ["B.J", "B.M.M."],
    "Arts, Humanities and Social Sciences": [
      "B.A/B.A (Hons)",
      "B.Voc.",
      "B.F.A.",
      "B.P.Ed.",
      "B.S.W.",
    ],
    Sciences: ["B.Sc/B.Sc (Hons)", "BS", "B.Sc B.Ed", "B.Sc M.Sc", "B.F.Sc."],
    Commerce: ["B.Com", "B.Com(Hons)", "BE"],
    "Computer Application and IT": ["B.C.A.", "BCA MCA"],
    Pharmacy: ["B.Pharma", "B.Pharma MBA"],
    Education: ["B.Ed.", "B.El.Ed.", "B.T."],
    "Hospitality and Tourism": ["BHM/BHMCT", "B.T.T.M.", "BTM"],
  },
  after10th: {
    Categories: [
      "Engineering and Architecture",
      "Management and Business Administration",
      "Medicine and Allied Sciences",
      "Law",
      "Animation and Design",
      "Media, Mass Communication and Journalism",
      "Arts, Humanities and Social Sciences",
      "Sciences",
      "Commerce",
      "Computer Application and IT",
      "Pharmacy",
      "Education",
      "Hospitality and Tourism",
      "Not Decided",
    ],
  },
  ugDiploma: {
    "Targeting Admissions": [
      "Targeting 2027 College Admissions",
      "Targeting 2028 College Admissions",
    ],
  },
  ugDegreePursuing: [
    "A.M.B.S.",
    "B.A.",
    "B.A. L.L.B",
    "B.A.(Hons)",
    "B.A.M.S.",
    "B.Agri",
    "B.Arch",
    "B.ASLP",
    "B.B.A",
    "B.B.A. L.L.B",
    "B.C.A.",
    "B.Com",
    "B.Com.L.L.B",
    "B.Com(Hons)",
    "B.D.S.",
    "B.Des",
    "B.Des M.Des",
    "B.Des MBA",
    "B.E /B.Tech",
    "B.Ed.",
    "B.Ed. Spl.Ed",
    "B.El.Ed.",
    "B.F.A.",
    "B.F.L.",
    "B.F.Sc.",
    "B.F.Tech",
    "B.H.Ed",
    "B.H.M.",
    "B.H.M.C.T.",
    "B.H.M.S.",
    "B.I.D.",
    "B.Ind.",
    "B.J.",
    "B.Lib.I.Sc.",
    "B.Lib.Sc.",
    "B.M.B.S.",
    "B.M.M.",
    "B.M.S",
    "B.N.Y.S.",
    "B.Nurs",
    "B.O.T.",
    "B.Optom",
    "B.Optom MBA",
    "B.P.A.",
    "B.P.Ed.",
    "B.P.O.",
    "B.P.T.",
    "B.Pharma",
    "B.Pharma MBA",
    "B.Plan",
    "B.R.S.",
    "B.R.Sc.",
    "B.S.M.S.",
    "B.S.Sc.",
    "B.S.W.",
    "B.Sc B.Ed",
    "B.Sc M.Sc",
    "B.Sc MBA",
    "B.Sc.",
    "B.Sc. L.L.B",
    "B.Sc.(Hons)",
    "B.Stat",
    "B.T.",
    "B.T.T.M.",
    "B.Tech M.Tech",
    "B.Tech MBA",
    "B.Text",
    "B.U.M.S.",
    "B.V.A.",
    "B.V.Sc.",
    "B.Voc.",
    "BA B.Ed",
    "BA MBA",
    "BAD",
    "BAG",
    "BAS",
    "BCA MCA",
    "BCJ",
    "BE",
    "BEM",
    "BFD",
    "BFIA",
    "BGD",
    "BHCT",
    "BLM",
    "BPR",
    "BPT MBA",
    "BS",
    "BTM",
    "CA",
    "CPL",
    "CS",
    "D.V.Sc.&A.H.",
    "ICWA",
    "L.L.B",
    "M.B.B.S.",
  ],
  pgAfterUG: {
    "Engineering and Architecture": [
      "M.E /M.Tech.",
      "M.S",
      "M.Arch",
      "P.G.D",
      "M.Phil.",
    ],
    "Management and Business Administration": [
      "MBA/PGDM",
      "P.G.D",
      "M.S",
      "M.Phil.",
      "Executive MBA",
    ],
    "Medicine and Allied Sciences": [
      "M.D.",
      "M.S.",
      "M.D.S.",
      "M.P.T.",
      "P.G.D",
    ],
    Law: ["L.L.M", "P.G.D", "M.Phil."],
    "Animation and Design": ["M.Des", "P.G.D", "M.Phil.", "PGDFD", "M.I.D."],
    "Media, Mass Communication and Journalism": ["P.G.D", "M.J", "M.Phil."],
    "Arts, Humanities and Social Sciences": [
      "M.A.",
      "M.Phil.",
      "M.S.W.",
      "M.F.A.",
      "P.G.D",
    ],
    Sciences: ["M.Sc.", "M.S", "M.Phil.", "P.G.D", "M.F.Sc."],
    Commerce: ["M.Com", "M.Phil.", "P.G.D", "M.Com (Hons)", "MFM"],
    "Computer Application and IT": [
      "M.C.A.",
      "P.G.D.C.A.",
      "P.G.D",
      "M.Phil.",
      "M.C.M",
    ],
    Pharmacy: ["M.Pharma", "P.G.D", "M.Phil."],
    Education: ["M.Ed.", "M.Phil.", "P.G.D"],
    "Hospitality and Tourism": [
      "MHM/MHMCT",
      "P.G.D",
      "M.T.T.M.",
      "MTM",
      "M.Phil.",
    ],
  },
};

export const educationData = {
  levels: {
    school: {
      label: "School",
      years: [
        "Class 6th",
        "Class 7th",
        "Class 8th",
        "Class 9th",
        "Class 10th",
        "Class 11th",
        "Class 12th",
        "Class 12th Passed",
      ],
      nextSteps: {
        "Class 12th Passed": "after12thCourses",
        "Class 12th": "after12thCourses",
        "Class 11th": "after12thCourses",
        "Class 10th": "after10thCourses",
        "Class 6th": "after10thCourses",
        "Class 7th": "after10thCourses",
        "Class 8th": "after10thCourses",
        "Class 9th": "after10thCourses",
      },
    },
    diploma: {
      label: "After 10th/UG Diploma",
      years: [
        "Targating 2025 admissions",
        "Targating 2026 admissions",
        "Targating 2027 admissions",
      ],
      nextSteps: {
        all: "diplomaCourses",
      },
    },
    undergraduate: {
      label: "UG Degree/Graduation",
      years: [
        "Targating 2025 admissions",
        "Targating 2026 admissions",
        "Targating 2027 admissions",
      ],
      nextSteps: {
        all: "pgCourses",
      },
    },
    postgraduate: {
      label: "PG Degree/Post Graduation",
      years: [
        "Targating 2025 admissions ",
        "Targating 2026 admissions ",
        "Targating 2027 admissions",
      ],
      nextSteps: {
        all: "pgCourses",
      },
    },
  },
  dates: {
    label: "12th Passed in",
  },
  courses: {
    after12thCourses: {
      Engineering: [
        "B.E /B.Tech",
        "B.Tech M.Tech (Integrated)",
        "B.Tech + MBA (Integrated)",
        "B.Arch",
        "B.Plan",
        "B.Des",
        "Marine Engineering",
        "Aerospace Engineering",
        "Chemical Engineering",
        "Biotechnology",
      ],
      Medical: [
        "MBBS",
        "BDS",
        "BAMS",
        "BHMS",
        "B.Pharm",
        "BSc Nursing",
        "BPT (Physiotherapy)",
        "BOT (Occupational Therapy)",
        "B.Optom (Optometry)",
        "Medical Lab Technology",
      ],
      Commerce: [
        "B.Com",
        "B.Com (Hons)",
        "BBA",
        "CA",
        "CS",
        "CMA (ICWA)",
        "BMS",
        "International Finance",
        "Banking & Insurance",
        "Financial Markets",
      ],
      Science: [
        "B.Sc",
        "B.Sc (Hons)",
        "B.Sc + M.Sc (Integrated)",
        "BCA",
        "B.Stat",
        "B.Tech Biotechnology",
        "B.F.Sc (Fisheries)",
        "B.Sc Agriculture",
        "B.Sc Forestry",
        "Aviation",
      ],
      "Arts & Humanities": [
        "BA",
        "BA (Hons)",
        "BFA",
        "BMS",
        "BMM",
        "BVA (Visual Arts)",
        "BSW (Social Work)",
        "B.Ed",
        "Psychology",
        "Foreign Languages",
      ],
      Law: ["LLB", "BA LLB", "BBA LLB", "B.Com LLB", "B.Sc LLB", "B.Tech LLB"],
      Design: [
        "B.Des Fashion",
        "B.Des Interior",
        "B.Des Product",
        "B.Des Graphic",
        "B.Des Animation",
        "B.Des UI/UX",
        "B.Des Industrial",
        "B.F.Tech",
      ],
      "Hotel Management": [
        "BHM",
        "BHMCT",
        "B.Sc Hospitality",
        "B.Sc Culinary Arts",
        "B.Sc Hotel Management",
        "BTTM (Tourism)",
      ],
    },
    after10thCourses: {
      Science: [
        "PCM",
        "PCB",
        "PCMB",
        "PCM with Computer Science",
        "PCM with Electronics",
        "PCB with Psychology",
        "PCB with Home Science",
      ],
      Commerce: [
        "Commerce with Maths",
        "Commerce without Maths",
        "Commerce with Statistics",
        "Commerce with Computer Science",
        "Commerce with Economics",
        "Business Studies",
      ],
      Arts: [
        "Arts/Humanities",
        "Fine Arts",
        "Performing Arts",
        "Languages",
        "Psychology",
        "Political Science",
        "History",
        "Geography",
      ],
      Diploma: [
        "Diploma in Engineering",
        "Diploma in Pharmacy",
        "Diploma in Hotel Management",
        "Diploma in Design",
        "Diploma in Architecture",
        "Diploma in Fashion Technology",
        "Diploma in Interior Design",
        "Diploma in Animation",
      ],
      Vocational: [
        "ITI Courses",
        "Healthcare",
        "Agriculture",
        "IT & Software",
        "Media & Entertainment",
        "Banking & Finance",
        "Retail",
        "Automotive",
      ],
    },
    diplomaCourses: {
      Engineering: [
        "Civil Engineering",
        "Mechanical Engineering",
        "Electrical Engineering",
        "Electronics Engineering",
        "Computer Engineering",
        "Automobile Engineering",
        "Chemical Engineering",
        "Mining Engineering",
        "Textile Engineering",
        "Tool & Die Making",
      ],
      "Non-Engineering": [
        "Pharmacy",
        "Hotel Management",
        "Fashion Design",
        "Interior Design",
        "Animation",
        "Film Making",
        "3D Animation",
        "Web Design",
        "Digital Marketing",
        "Medical Lab Technology",
      ],
    },
    ugCourses: {
      Engineering: [
        "Computer Science",
        "Information Technology",
        "Mechanical",
        "Civil",
        "Electrical",
        "Electronics",
        "Chemical",
        "Aerospace",
        "Biotechnology",
        "Robotics",
      ],
      Medical: [
        "MBBS",
        "BDS",
        "BAMS",
        "BHMS",
        "Nursing",
        "Pharmacy",
        "Physiotherapy",
        "Occupational Therapy",
        "Medical Imaging",
        "Speech Therapy",
      ],
      Commerce: [
        "Accounting & Finance",
        "Banking & Insurance",
        "Business Administration",
        "Economics",
        "Financial Markets",
        "International Business",
        "Marketing",
        "Human Resources",
        "Taxation",
        "Risk Management",
      ],
      Science: [
        "Physics",
        "Chemistry",
        "Mathematics",
        "Biology",
        "Computer Science",
        "Statistics",
        "Environmental Science",
        "Microbiology",
        "Biotechnology",
        "Marine Science",
      ],
    },
    pgCourses: {
      Engineering: [
        "M.Tech in Computer Science",
        "M.Tech in Electronics",
        "M.Tech in Mechanical",
        "M.Tech in Civil",
        "M.Tech in AI & ML",
        "M.Tech in Data Science",
        "M.Tech in Robotics",
        "M.Tech in Renewable Energy",
        "M.Tech in Nanotechnology",
        "M.Tech in Biomedical",
      ],
      Medical: [
        "MD",
        "MS",
        "DNB",
        "M.Pharm",
        "MPT",
        "M.Sc Medical",
        "MDS",
        "MD Ayurveda",
        "MD Homeopathy",
        "Masters in Public Health",
      ],
      Management: [
        "MBA Finance",
        "MBA Marketing",
        "MBA HR",
        "MBA Operations",
        "MBA International Business",
        "MBA Business Analytics",
        "MBA Healthcare",
        "MBA IT",
        "MBA Logistics",
        "MBA Entrepreneurship",
      ],
      Science: [
        "M.Sc Physics",
        "M.Sc Chemistry",
        "M.Sc Mathematics",
        "MCA",
        "M.Sc Statistics",
        "M.Sc Biotechnology",
        "M.Sc Environmental Science",
        "M.Sc Data Science",
        "M.Sc Astronomy",
        "M.Sc Artificial Intelligence",
      ],
      Arts: [
        "MA Economics",
        "MA English",
        "MA Psychology",
        "MA Political Science",
        "MA History",
        "MA Sociology",
        "MA Philosophy",
        "MA International Relations",
        "MA Development Studies",
        "MA Media & Communications",
      ],
    },
  },
};
